// 0x0E000488
const GeoLayout bob_geo_000488[] = {
   GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
   GEO_OPEN_NODE(),
      GEO_ZBUFFER(0),
      GEO_OPEN_NODE(),
         GEO_NODE_ORTHO(100),
         GEO_OPEN_NODE(),
            GEO_BACKGROUND_DYN(BACKGROUND_OCEAN_SKY, DYN_geo_skybox_main),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
      GEO_ZBUFFER(1),
      GEO_OPEN_NODE(),
         GEO_CAMERA_FRUSTUM_WITH_FUNC_DYN(45, 100, 30000, DYN_geo_camera_fov),
         GEO_OPEN_NODE(),
            GEO_CAMERA_DYN(1, 0, 2000, 6000, 3072, 0, -4608, DYN_geo_camera_main),
            GEO_OPEN_NODE(),
               GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_seg7_dl_07004390),
               GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_seg7_dl_07009D80),
               GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bob_seg7_dl_0700A470),
               GEO_DISPLAY_LIST(LAYER_ALPHA, bob_seg7_dl_0700A920),
               GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_seg7_dl_0700DD18),
               GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_seg7_dl_0700E338),
               GEO_RENDER_OBJ(),
               GEO_ASM_DYN(0, DYN_geo_envfx_main),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
      GEO_ZBUFFER(0),
      GEO_OPEN_NODE(),
         GEO_ASM_DYN(0, DYN_geo_cannon_circle_base),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
