// 0x0E000E00
const GeoLayout lll_geo_000E00[] = {
   GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
   GEO_OPEN_NODE(),
      GEO_ZBUFFER(0),
      GEO_OPEN_NODE(),
         GEO_NODE_ORTHO(100),
         GEO_OPEN_NODE(),
            GEO_BACKGROUND_DYN(BACKGROUND_FLAMING_SKY, DYN_geo_skybox_main),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
      GEO_ZBUFFER(1),
      GEO_OPEN_NODE(),
         GEO_CAMERA_FRUSTUM_WITH_FUNC_DYN(64, 100, 20000, DYN_geo_camera_fov),
         GEO_OPEN_NODE(),
            GEO_CAMERA_DYN(1, 0, 2000, 6000, 0, 0, -8192, DYN_geo_camera_main),
            GEO_OPEN_NODE(),
               GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_seg7_dl_070134E0),
               GEO_DISPLAY_LIST(LAYER_ALPHA, lll_seg7_dl_070138F8),
               GEO_DISPLAY_LIST(LAYER_ALPHA, lll_seg7_dl_070137C0),
               GEO_ASM_DYN(   0, DYN_geo_movtex_pause_control),
               GEO_ASM_DYN(0x2201, DYN_geo_movtex_draw_nocolor),
               GEO_RENDER_OBJ(),
               GEO_ASM_DYN(  12, DYN_geo_envfx_main),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
