// 0x0E0009D0
const GeoLayout rr_geo_0009D0[] = {
   GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
   GEO_OPEN_NODE(),
      GEO_ZBUFFER(0),
      GEO_OPEN_NODE(),
         GEO_NODE_ORTHO(100),
         GEO_OPEN_NODE(),
            GEO_BACKGROUND_DYN(BACKGROUND_BELOW_CLOUDS, DYN_geo_skybox_main),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
      GEO_ZBUFFER(1),
      GEO_OPEN_NODE(),
         GEO_CAMERA_FRUSTUM_WITH_FUNC_DYN(45, 100, 20000, DYN_geo_camera_fov),
         GEO_OPEN_NODE(),
            GEO_CAMERA_DYN(14, 0, 2000, 6000, 0, 0, -8000, DYN_geo_camera_main),
            GEO_OPEN_NODE(),
               GEO_ASM_DYN(0, DYN_geo_exec_flying_carpet_timer_update),
               GEO_DISPLAY_LIST(LAYER_ALPHA, dl_cruiser_metal_holes),
               GEO_RENDER_OBJ(),
               GEO_ASM_DYN(0, DYN_geo_envfx_main),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
      GEO_ZBUFFER(0),
      GEO_OPEN_NODE(),
         GEO_ASM_DYN(0, DYN_geo_cannon_circle_base),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
