// 0x0E000A70
const GeoLayout ttm_geo_000A70[] = {
   GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
   GEO_OPEN_NODE(),
      GEO_ZBUFFER(0),
      GEO_OPEN_NODE(),
         GEO_NODE_ORTHO(100),
         GEO_OPEN_NODE(),
            GEO_BACKGROUND_DYN(BACKGROUND_OCEAN_SKY, DYN_geo_skybox_main),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
      GEO_ZBUFFER(1),
      GEO_OPEN_NODE(),
         GEO_CAMERA_FRUSTUM_WITH_FUNC_DYN(45, 100, 12800, DYN_geo_camera_fov),
         GEO_OPEN_NODE(),
            GEO_CAMERA_DYN(1, 0, 2000, 6000, 0, -2200, 0, DYN_geo_camera_main),
            GEO_OPEN_NODE(),
               GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_seg7_dl_0700A120),
               GEO_DISPLAY_LIST(LAYER_OPAQUE, ttm_seg7_dl_0700A2E0),
               GEO_RENDER_OBJ(),
               GEO_ASM_DYN(    0, DYN_geo_painting_update),
               GEO_ASM_DYN(PAINTING_ID(0, 2), DYN_geo_painting_draw),
               GEO_ASM_DYN(    0, DYN_geo_movtex_pause_control),
               GEO_ASM_DYN(0x3601, DYN_geo_movtex_draw_nocolor),
               GEO_ASM_DYN(0x3602, DYN_geo_movtex_draw_nocolor),
               GEO_ASM_DYN(0x3603, DYN_geo_movtex_draw_nocolor),
               GEO_ASM_DYN(0x3604, DYN_geo_movtex_draw_nocolor),
               GEO_ASM_DYN(0x3605, DYN_geo_movtex_draw_nocolor),
               GEO_ASM_DYN(0x3601, DYN_geo_movtex_draw_water_regions),
               GEO_ASM_DYN(    0, DYN_geo_envfx_main),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
      GEO_ZBUFFER(0),
      GEO_OPEN_NODE(),
         GEO_ASM_DYN(0, DYN_geo_cannon_circle_base),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
