// 0x0E000618
const GeoLayout geo_bitdw_000618[] = {
   GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
   GEO_OPEN_NODE(),
      GEO_ZBUFFER(0),
      GEO_OPEN_NODE(),
         GEO_NODE_ORTHO(100),
         GEO_OPEN_NODE(),
            GEO_BACKGROUND_DYN(BACKGROUND_GREEN_SKY, DYN_geo_skybox_main),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
      GEO_ZBUFFER(1),
      GEO_OPEN_NODE(),
         GEO_CAMERA_FRUSTUM_WITH_FUNC_DYN(45, 100, 20000, DYN_geo_camera_fov),
         GEO_OPEN_NODE(),
            GEO_CAMERA_DYN(14, 0, 2000, 6000, 0, 0, 0, DYN_geo_camera_main),
            GEO_OPEN_NODE(),
               GEO_DISPLAY_LIST(LAYER_ALPHA, bitdw_seg7_dl_070020C8),
               GEO_RENDER_OBJ(),
               GEO_ASM_DYN(0, DYN_geo_envfx_main),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
